sudo: required
services:
  - docker

before_install:
  - docker build -t maw488/react-test -f ./client/Dockerfile.dev

script:
  - docker run maw488/react-test npm test

after_success:
  - docker build -t maw488/multi-client ./client
  - docker build -t maw488/multi-nginx ./nginx
  - docker build -t maw488/multi-server ./server
  - docker build -t maw488/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push maw488/multi-client
  - docker push maw488/multi-nginx
  - docker push maw488/multi-server
  - docker push maw488/multi-worker
